name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 12.x

      - uses: actions/cache@v2
        id: yarn-cache
        with:
            path: '**/node_modules'
            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Cypress binary
        run: yarn cypress install

      - name: install yarn
        run: brew install yarn
        
      - name: install dhis2 cli
        run: yarn global add @dhis2/cli
        
      - name: start dhis2 server
        run: d2 cluster up mycluster --dhis2-version 2.35.5 --seed --db-version 2.35 --update --port 9000
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3000, http://localhost:9000'
          wait-on-timeout: 180
          browser: chrome
          headless: true
          record: true
          config-file: ./cypress.json
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_dhis2BaseUrl: http://localhost:9000
          CYPRESS_dhis2Username: admin
          CYPRESS_dhis2Password: district
          CYPRESS_dhis2DataTestPrefix: dhis2-smsconfiguration
          
          
          
        
      
