name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: |
            yarn build
            d2 cluster up mycluster --dhis2-version 2.35.5 --seed --db-version 2.35 --update --port 9000
          wait-on: 'http://localhost:3000, http://localhost:9000'
          wait-on-timeout: 600
          browser: chrome
          headless: true
          record: true
          config-file: ./cypress.json
          command: yarn cy:run
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_dhis2BaseUrl: http://localhost:9000
          CYPRESS_dhis2Username: admin
          CYPRESS_dhis2Password: district
          CYPRESS_dhis2DataTestPrefix: dhis2-smsconfiguration
          
          
          
        
      
