name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@v1
        with:
            node-version: 12.x
            
      - uses: actions/cache@v2
        id: yarn-cache
        with:
            path: '**/node_modules'
            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install yarn
        run: brew install yarn
      
      - name: Install dhis2 cli
        run: yarn global add @dhis2/cli
        
      - name: Start dhis2 server
        run: d2 cluster up master --channel dev --db-version dev --dhis2-version master --seed
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3000, http://localhost:8080'
          wait-on-timeout: 30
          browser: chrome
          headless: true
          #record: true
          #parallel: true
          #group: 'E2E'
          config-file: ./cypress.json
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_dhis2BaseUrl: http://localhost:8080
          CYPRESS_dhis2Username: admin
          CYPRESS_dhis2Password: district
          CYPRESS_dhis2DataTestPrefix: dhis2-smsconfiguration
          
          
          
        
      
