name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@v1
        with:
            node-version: 12.x

      - name: Install yarn
        run: brew install yarn
        
      - name: Install d2-app-scripts
        run: yarn add --dev @dhis2/cli-app-scripts
        
      - name: Start server
        run: yarn start
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 30
          command: yarn cy:run:stub
          browser: chrome
          headless: true
          #record: true
          #parallel: true
          #group: 'E2E'
          config-file: ./cypress.json
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_dhis2BaseUrl: http://localhost:8080
          CYPRESS_dhis2Username: admin
          CYPRESS_dhis2Password: district
          CYPRESS_dhis2DataTestPrefix: dhis2-smsconfiguration
          
          
          
        
      
